import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
      >
        <header className="bg-white shadow-md fixed top-0 left-0 w-full z-10">
          <div className="container mx-auto flex items-center justify-center p-4">
            <h1 className="text-2xl font-bold">My Library</h1>
          </div>
        </header>
        <main className="pt-20 container mx-auto px-4">{children}</main>
        <footer className="bg-white shadow-md fixed bottom-0 left-0 w-full p-4 flex justify-between items-center text-sm">
          <p>&copy; {new Date().getFullYear()} Example Company</p>
          <Link className="hover:text-gray-600" href="/legal">
            Legal
          </Link>
        </footer>
      </body>
    </html>
  );
}
